version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3-stretch-node
        environment:
          BUNDLER_VERSION: 2.0.1
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: install dependencies
          command:
            gem update --system
            gem install bundler
      - ruby/bundle-install
