version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    working_directory: ~/sweater_weather
    docker:
      - image: circleci/ruby:2.5.3-stretch
        environment:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: sweater_weather
      - image: postgres:12.3
        environment:
          POSTGRES_USER: sweater_weather
          POSTGRES_DB: sweater_weather_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      - run: dockerize -wait tcp://localhost:3000 -timeout 1m
      - run: bundle install
      - run: bundle exec rake db:setup
      - run: bundle exec rspec
